
[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "Meslo LGM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Meslo LGM Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Meslo LGM Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "Meslo LGM Nerd Font"
style = "Regular"
    
[window]
opacity = 0.80

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
